refactor(levm): make runner more usefull for debugging (#3601)
**Motivation**

Make runner more usefull for debugging. 
- When running specific tests, stop showing all the directories parsed
to get the tests, and only show the ones where the selected tests are
in.
- Give more detail about the failing tests.
- Don't saturate console output with endless log messages.

**Description**

This pr makes changes in the runners code, now when parsing the tests
only the relative paths of the directories parsed are printed, not just
the names of the directories. (Closes #3578)

To see this change you can run:

```bash
cd cmd/ef_tests/state
make test-levm
```

This command downloads and runs all tests only for levm. If you want to
run specific tests you can run:

```bash
cd cmd/ef_tests/state
cargo test --package ef_tests-state --test all --release -- --forks Prague,Cancun --tests blob_tx_attribute_calldata_opcodes.json
```

It also incorporates a new `paths` flag for running tests given their
paths. The flag is to parse directly a test file instead of going over
all directories trying to find the file only by its name. (This also
Closes #3578)

You can try it by running:

```bash
cd cmd/ef_tests/state
cargo test --package ef_tests-state --test all --release -- --forks Prague,Cancun --summary  --paths --tests LegacyTests/Cancun/GeneralStateTests/Shanghai/stEIP3855-push0/push0.json,GeneralStateTests/Shanghai/stEIP3855-push0/push0.json,GeneralStateTests/stBadOpcode/invalidAddr.json,LegacyTests/Cancun/GeneralStateTests/stBadOpcode/invalidAddr.json
```

This should be the same as running the example we have in the read me:

```bash
cd cmd/ef_tests/state
cargo test --package ef_tests-state --test all --release -- --forks Prague,Cancun --summary --tests push0.json,invalidAddr.json
```

For failing tests, now the code shows the name and the path of the
failing tests, and it mentions the runner and the line where the error
was thrown. (Closes #3579)
Also, to provide more information about the tests, this pr also includes
parsing more information from the test's .json in the `EFTestReport`
struct. This information is saved in the fields `description`, `url` and
`reference_spec`. `url` and `reference_spec` refer to the url to the
python test, and to the repo of the EIP the tests refer to,
respectively. It also lists
[https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html#](https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html#)
as a resource for understanding the tests. (Closes #3581)

Now when a test fails it looks like this:
```
state_tests/frontier/precompiles/precompile_absence: 6/6 (100.00%)
state_tests/cancun/eip6780_selfdestruct/dynamic_create2_selfdestruct_collision: 12/12 (100.00%)
GeneralStateTests/stTransitionTest: 12/12 (100.00%)
state_tests/cancun/eip4844_blobs/blob_txs: 1173/1174 (99.91%)


Running failed tests with REVM...
Re-running failed tests with REVM 1/1 - 00:00
Failing Test: 
Test name: tests/cancun/eip4844_blobs/test_blob_txs.py::test_blob_tx_attribute_calldata_opcodes[fork_Cancun-state_test-tx_gas_500000-empty-opcode_CALLDATACOPY]
Test path: /Users/camiladiielsi/Documents/ethrex/cmd/ef_tests/state/vectors/state_tests/cancun/eip4844_blobs/blob_txs_blob_tx_attribute_calldata_opcodes.json

Test description: Test calldata related opcodes to verify their behavior is not affected by blobs.

    - CALLDATALOAD
    - CALLDATASIZE
    - CALLDATACOPY

Note: The following links may help when debugging `ef-tests`:
- https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html#
- Test reference spec: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md
- Test url: https://github.com/ethereum/execution-spec-tests/tree/v4.5.0/tests/cancun/eip4844_blobs/test_blob_txs.py#L1218

Error: Internal(MainRunnerInternal("Non-internal error raised when executing revm. This should not happen: Err(Internal(Custom(\"Error at LEVM::get_state_transitions() thrown in REVM runner line: 391 when executing ensure_post_state()\")))"))
error: test failed, to rerun pass `-p ef_tests-state --test all`
```
(Note: the error shown was fabricated by changing the post hash value of
the test.)

Another change introduced is that now there are no more endless log
messages, the messages are overwritten with actualized information of
the tests that are being executed. (Closes #3580) You can see that by
running any of the commands mentioned.

This solution is meant to be a temporary fix since there's a new runner
being programmed from scratch to improve the user experience.