feat(l2): reject blob transaction from the rpc client (#2856)
**Motivation**

Blob transactions (EIP-4844) are not to be supported in the L2. If we
accept this type of transactions they will never leave the mempool
because they won't be included in any block

**Description**

Added a `#[cfg(feature = "l2")]` block to log a debug message and return
an `RpcErr` when EIP-4844 transactions are encountered in L2
environments.

**How to test**

Run:
```sh
cast send --rpc-url http://localhost:1729 --private-key 0xbcdf20249abf0ed6d944c0288fad489e33f66b3960d9e6229c1cd214ed3bbe31 0xb4b46bdaa835f8e4b4d8e208b6559cd267851051 --blob --path <path_to_file>
```
The file can have anything while its size is less than 128kb.

Expected output:
```sh
Error: server returned an error response: error code -39000: Invalid Ethex L2 message: EIP-4844 transactions are not supported in the L2
```

**What's next**

If `based` is supported on L2 #2857 has to be addressed

Closes #2855