feat(l1)!: fail opening DB without schema version (#5597)
**Motivation**

We're currently opening the Store backend before checking the DB schema
version matches. This can lead to data loss in case the RocksDB schema
is changed.

**Description**

This PR changes the metadata to be stored in JSON format in a
backend-agnostic way. This allows for inspecting the DB version without
starting ethrex. Example:

```text
$ cat "~/.local/share/ethrex/metadata.json"
{
  "schema_version": 1
}
```

It also allows for more easily extending the check with more
validations, for example, for backend type.

Additionally, it also fails with a clear error when trying to run a new
ethrex version on an old DB without this versioning scheme:

```
2025-12-11T14:33:47.045029Z  INFO Opening storage engine engine=RocksDB path="/Users/mega/Library/Application Support/ethrex"
Error: Incompatible DB Version: found 0, expected 1. Please run `ethrex removedb` and restart node

Location:
    /Users/mega/execution/ethrex/cmd/ethrex/initializers.rs:400:24
```

Closes #5541