fix(l1): prevent panic in `eth68/Receipts` message handling (#4268)
**Motivation**
I ran into the following panic while running ethrex on sepolia testnet:
```
thread 'tokio-runtime-worker' panicked at crates/networking/p2p/rlpx/eth/eth68/receipts.rs:30:69:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR prevents this panic from happening
<!-- Why does this pull request exist? What are its goals? -->

**Description**
* (eth68 message) `Receipts::new` no longer asumes we have at least one
receipt for a given block
<!-- A clear and concise general description of the changes this PR
introduces -->

<!-- Link to issues: Resolves #111, Resolves #222 -->

Closes #issue_number