fix(l2): correct private key for load test account (#2837)
**Motivation**

After the changes introduced in #2781. The rich account needed for the
load test no longer has funds to make the deploy and the transactions.

**Description**

Change the private key to one of the rich accounts that is used on the
initial deposit in the deployment of the L2

**How to test**

Running: `cargo run --manifest-path ../../cmd/load_test/Cargo.toml -- -k
../../test_data/private_keys.txt -t erc20 -N 50 -n
http://localhost:1729`

This won't lead to panic.

But in main we get:
```
ERC20 Load test starting
Deploying ERC20 contract...
thread 'main' panicked at cmd/load_test/src/main.rs:358:18:
Failed to deploy ERC20 contract: eth_sendRawTransaction request error: Invalid params: Account does not have enough balance to cover the tx cost

Caused by:
    Invalid params: Account does not have enough balance to cover the tx cost
```